export const FIELD_GUIDE_EN = {
    visaType: "This decides which counter you go to at IVAC. The patient and the attendant both take MEDICAL / MEDICAL ATTENDANT VISA — there is no separate option. For a holiday choose TOURIST VISA, for office work BUSINESS VISA, for study STUDENT VISA, and for passing through India to another country TRANSIT VISA. If you pick the wrong type, the counter sends you back.",
    webFileNumber: "Web File Number — it is printed at the top of the PDF you download when the online application is finished (it starts with BGDD).",
    applicationId: "Your application ID, printed at the top of the web file. It changes if you make a new application — do not keep using the old one.",
    tempApplicationId: 'The temporary ID you get when you save a half-filled form. With it you can later return through "Complete Partially Filled Form".',
    passportNo: "Your passport number exactly as in the passport — English letters first, then digits (e.g. A01234567). Do not add spaces.",
    fullName: "Your full name exactly as written in the passport, in capital letters. If even one letter differs, the counter sends you back.",
    gender: "As in your passport — MALE / FEMALE / TRANSGENDER.",
    dob: "Date of birth as DD/MM/YYYY — the date in your passport, not your NID. If the two differ, use the passport one.",
    citizenshipNo: "Your NID number (10, 13 or 17 digits). If you have no NID, your birth registration number.",
    surname: "Whatever is in the Surname box of your passport. If that box is empty, do not leave this one empty — enter the last part of your name from the passport, otherwise the form is not accepted.",
    givenName: "The Given Name in your passport — the rest of your name, without the Surname.",
    changedName: "Have you ever changed your name? If not, NO.",
    previousSurname: "If you changed your name, your previous Surname; otherwise leave it blank.",
    previousName: "If you changed your name, your previous full name; otherwise leave it blank.",
    townOfBirth: "The town/thana you were born in — whatever is written under Place of Birth in your passport.",
    countryOfBirth: "Country of birth — BANGLADESH.",
    nationality: "Nationality — BANGLADESH.",
    nationalityBy: "If you are a citizen by birth, BY BIRTH. If you became a citizen through marriage or by application, choose that.",
    previousNationality: "Were you a citizen of another country before? If you were born in Bangladesh and are a Bangladeshi citizen, leave this blank — do not enter BANGLADESH; this box is for a previous citizenship, not your current one.",
    religion: "Religion — ISLAM / HINDU / CHRISTIAN / BUDDHIST. If yours is not in the list, OTHERS.",
    religionOther: "If you chose OTHERS above, write the name of your religion here.",
    identificationMarks: "A permanent mark on your body — as written in your passport. If there is none, NO VISIBLE MARK.",
    education: "The portal's list is in English and our certificates are Bangladeshi — here is how they match: SSC/Dakhil → MATRICULATION. HSC/Alim/Diploma → HIGHER SECONDARY. Honours/Pass course/Degree → GRADUATE. Masters/MBA/MPhil/PhD → POST GRADUATE. Doctor, engineer, lawyer, chartered accountant → PROFESSIONAL. Did not pass SSC → BELOW MATRICULATION. No schooling at all → ILLITERATE. The box cannot be left empty, so do not hesitate to choose ILLITERATE — it does not count against you.",
    passportCountryOfIssue: "The country that issued your passport — BANGLADESH.",
    passportPlaceOfIssue: "The Issuing Authority in your passport — e.g. DHAKA, AGARGAON. It is written on the last page of the passport.",
    passportIssueDate: "Passport issue date, DD/MM/YYYY.",
    passportExpiryDate: "Expiry date, DD/MM/YYYY. It must be at least 6 months after your travel date, otherwise the visa is not issued.",
    otherPassport: "Do you have any other passport or identity document? If not, NO — then the boxes below are not needed.",
    otherPassportCountry: 'The country of that other passport. If it is another, older Bangladeshi passport, BANGLADESH. If you answered NO to "Hold any other valid passport?" above, this box is not needed at all.',
    otherPassportNo: "The number of that passport.",
    otherPassportIssueDate: "The issue date of that passport, DD/MM/YYYY.",
    otherPassportPlaceOfIssue: "Where that passport was issued from.",
    otherPassportNationality: "The nationality written in that passport — usually BANGLADESH. If you answered NO above, leave it blank.",
    presentHouseStreet: "Where you live now — house and road number. It must match the address on your utility bill.",
    presentVillageTown: "Name of your village/neighbourhood/area.",
    presentCountry: "BANGLADESH.",
    presentState: "Your division — DHAKA, CHATTOGRAM, KHULNA and so on.",
    presentDistrict: "Your district.",
    presentPostal: "Post code, 4 digits (e.g. 1207).",
    presentPhone: "Your home landline, if you have one. If not, just enter your mobile number.",
    presentMobile: "Mobile number, 11 digits, starting with 0.",
    presentEmail: "Email address — news about your visa comes here, so give an email you actually use.",
    permanentSame: "If your permanent address is the same as your present one, YES — the boxes below then fill in by themselves.",
    permHouseStreet: "House and road of your permanent address — usually the one written on your NID.",
    permVillageTown: "Village/neighbourhood of your permanent address.",
    permState: 'Division of your permanent address. The portal calls this box "State / Province", but it wants the division — DHAKA, CHATTOGRAM, KHULNA, RAJSHAHI, BARISHAL, SYLHET, RANGPUR or MYMENSINGH. Not the district; there is a separate box for the district.',
    permDistrict: "District of your permanent address.",
    fatherName: "Your father's full name — exactly as written in your passport.",
    fatherNationality: "Father's nationality — BANGLADESH.",
    fatherPrevNationality: "Your father's previous citizenship, if it changed. If it did not change, his current one — enter BANGLADESH; leaving it empty blocks the form.",
    fatherPlaceOfBirth: "Your father's place of birth — name of the town/thana. If you do not know it, your own place of birth is usually right.",
    fatherCountryOfBirth: "Your father's country of birth — BANGLADESH. (Even if he was born before 1971, write BANGLADESH.)",
    motherName: "Your mother's full name — as written in your passport. The spelling must match; if it is one way in the passport and another in the form, you get stuck at the counter.",
    motherNationality: "Mother's nationality — BANGLADESH.",
    motherPrevNationality: "Your mother's previous citizenship, if it changed. If it did not change, BANGLADESH.",
    motherPlaceOfBirth: "Your mother's place of birth — name of the town/thana.",
    motherCountryOfBirth: "Your mother's country of birth — BANGLADESH.",
    maritalStatus: "MARRIED / SINGLE / DIVORCED / WIDOWED.",
    spouseName: "If married, your husband's/wife's full name, as in their passport. If they are travelling with you, the name must be the same in both forms.",
    spouseNationality: "Husband's/wife's nationality — BANGLADESH.",
    spousePrevNationality: "Your husband's/wife's previous citizenship, if it changed. If it did not change, BANGLADESH.",
    spousePlaceOfBirth: "Your husband's/wife's place of birth.",
    spouseCountryOfBirth: "Your husband's/wife's country of birth — BANGLADESH.",
    grandparentsPak: "Whether your paternal or maternal grandparents were Pakistani nationals. If not, NO. A false answer gets the visa cancelled later.",
    grandparentsDetails: "If you answered YES above, you must write the details.",
    occupation: "Occupation — SERVICE (a job), BUSINESSMAN, HOUSE WIFE, STUDENT, RETIRED and so on. If you are a housewife, HOUSE WIFE; do not leave it empty.",
    occupationOther: "If your occupation is not in the list, write it here.",
    employerName: "Name of the office/organisation. If you are a housewife or a student, not your own — give your husband's or father's organisation; that is what the form wants.",
    designation: "Job title — e.g. SOFTWARE ENGINEER, FARMER. If you are a housewife or a student, your husband's/father's job title.",
    employerAddress: "Full address of the office. If you are a housewife or a student, the address of your husband's/father's office.",
    employerPhone: "Office phone number. If you are a housewife or a student, your husband's/father's office number.",
    pastOccupation: "Work you did before but no longer do. Your current occupation has its own box above — do not write it again here. Had a job → PRIVATE SERVICE or GOVERNMENT SERVICE, business → BUSINESS PERSON, retired → RETIRED, were a student → STUDENT. If you did nothing before (e.g. a lifelong housewife), leave the box empty — no need to assume anything.",
    militaryService: "Were you ever in the army/police/a paramilitary force? If not, NO.",
    militaryOrg: "Which force.",
    militaryDesignation: "Your designation there.",
    militaryRank: "Your rank.",
    militaryPosting: "Where your last posting was.",
    occupationDetailsOf: "If you have no job or business of your own, whose occupation you are giving — SPOUSE (your husband's) if you are a housewife, FATHER (your father's) if you are a student or a child. Once this is set, the office boxes below show whose details are being asked for.",
    refIndiaName: "The name of someone you know in India. If there is no one, you can give the hospital's name — the box cannot be left empty.",
    refIndiaAddress: "Address of your reference in India.",
    refIndiaState: "State of your reference.",
    refIndiaDistrict: "District of your reference.",
    refIndiaPhone: "Phone number of your reference.",
    refHomeName: "One reference in Bangladesh — a relative or acquaintance who is not travelling with you.",
    refHomeAddress: "Their address.",
    refHomeAddress2: "The rest of the address.",
    refHomePhone: "Their mobile number — give a working number; the mission may call it.",
    visaPurpose: "Patient = MEDICAL VISA (M1), attendant = MEDICAL VISA (M2).",
    arrivalDate: "Expected date of arriving in India, DD/MM/YYYY. The visa's validity is counted from the day it is issued, not from this date.",
    mission: "The Indian mission you are applying to — for Dhaka, DHAKA.",
    durationDays: "Visa duration in months, not days. Usually 12 for a medical visa.",
    noOfEntries: "How many times you may go in and out — treatment may need several trips, so MULTIPLE.",
    portOfArrival: "Which way you will enter — by plane, BY AIR/ HARIDASPUR; through Benapole, BY ROAD HARIDASPUR.",
    portOfExit: "Which way you will leave India. In most cases the same way you enter — then enter exactly the same value as the box above. By air, BY AIR/ HARIDASPUR; through Benapole-Haridaspur, BY ROAD HARIDASPUR. The text must match exactly — the portal does not accept just HARIDASPUR; the route is needed with it.",
    placesToVisit: "The places you will go to in India — be sure to include the hospital's city, e.g. VELLORE, CHENNAI.",
    medicalRole: "Patient or attendant — PATIENT means M1, ATTENDANT means M2.",
    attendantOf: "If you are the attendant, the patient's full name, as in the patient's passport.",
    attendantOfPassport: "The patient's passport number.",
    illness: "What the illness is — the name written in the doctor's papers, in English.",
    hospitalName: "The hospital in India you are going to — e.g. CHRISTIAN MEDICAL COLLEGE.",
    hospitalAddress: "That hospital's address.",
    doctorName: "The name of the doctor in India, if you know it.",
    hospitalPhone: "The hospital's phone number.",
    hospitalEmail: "The hospital's email.",
    medicalCertNo: "The number on the hospital's letter/appointment, if there is one.",
    homeHospitalName: "The hospital/doctor in Bangladesh who referred you.",
    homeHospitalAddress: "That hospital's address.",
    homeDoctorName: "The name of the doctor in Bangladesh — as written on the referral paper.",
    homeHospitalPhone: "That hospital's phone.",
    homeHospitalEmail: "That hospital's email.",
    hasPreviousVisa: "Have you ever had an Indian visa before? If so, YES — if you hide it, it is found out later.",
    visaRefused: "Has a visa ever been cancelled or refused? If so, YES, and the reason below.",
    saarcVisited: "Whether you have been to a SAARC country (Pakistan, Nepal, Sri Lanka...) in the last 3 years.",
    oldVisaNo: "The number of your previous visa.",
    oldVisaType: "Type of the previous visa — e.g. MEDICAL VISA, TOURIST VISA.",
    oldVisaIssuePlace: "Where the previous visa was issued from.",
    oldVisaIssueDate: "Date of the previous visa, DD/MM/YYYY.",
    prevVisitAddress: "Where you stayed in India last time.",
    refuseDetails: "If a visa was refused, when, where and for what reason.",
    countriesVisited: "The countries you have been to in the last 10 years, separated by commas.",
    stayName: "Where you will stay in India — if in the hospital's guest house, the hospital's name; if in a hotel, the hotel's name.",
    stayAddress: "The full address of that place.",
    stayState: "State — for Vellore, TAMIL NADU.",
    stayDistrict: "District — for Vellore, VELLORE.",
    stayPhone: "The phone number there.",
    stayEmail: "The email there.",
    attendantOfDob: "The patient's date of birth, DD/MM/YYYY.",
    attendantOfNationality: "The patient's nationality — BANGLADESH.",
    attendantRelationship: 'Exactly what is written in the "Relationship with the patient" box of the invitation letter — SPOUSE, MOTHER IN LAW, SON. Mind the direction: this says who you are to the patient, not who the patient is to you. The cover letter is written in exactly this direction; writing it the other way round puts false information on the visa papers.',
    attendantOfApplicationId: "The patient's application ID. The patient's application must be made first, then the attendant's — the M2 form is not accepted without this ID.",
    decArrested: 'Portal question 1: "Have you ever been arrested / prosecuted / convicted by Court of Law of any country?" — whether you have ever been arrested, prosecuted or convicted by a court in any country. If YES, you must write the details.',
    decDeported: 'Portal question 2: "Have you ever been refused entry / deported by any country including India?" — whether any country, India included, has ever refused you entry or sent you back.',
    decTrafficking: 'Portal question 3: "Human trafficking / Drug trafficking / Child abuse / Crime against women / Economic offense / Financial fraud" — not only drugs; crimes against women and economic offences are also part of this question.',
    decTerrorism: 'Portal question 4: "Cyber crime / Terrorist activities / Sabotage / Espionage / Genocide / Political killing / other act of violence" — cyber crime is counted here too.',
    decGlorifyTerror: 'Portal question 5: "Have you ever by any means or medium, expressed views that justify or glorify terrorist violence...?" — by any medium; a Facebook post counts too.',
    decAsylum: 'Portal question 6: "Have you sought asylum (political or otherwise) in any country?" — whether you have sought asylum for political or any other reason.',
    decVerified: 'The final declaration: "I hereby declare that the information furnished above is correct... in case the information is found false at any stage, I am liable for legal action / deportation / blacklisting." If you choose Yes here, the tick on the page is put in automatically; if you leave it empty, it is not. Remember this is an oath made in your name — look over the form yourself once before choosing Yes. The final Submit, though, is never pressed by the extension; that is yours to press.',
    photoCrop: "The portal cuts a square out of your photo, and its script starts that square from the top-left corner of the photo — which in most photos is forehead and ceiling. Tell it here where your face is: TOP (head right at the top), UPPER (usually this one), CENTRE (face in the middle of the photo), LOWER. The extension crops at the same place when it shrinks the photo, and places the portal's crop box the same way — the same result in both places.",
    stayDays: 'How many days you will stay in India. Enter what the hospital wrote in the "Tentative duration of Stay(Days)" box of the invitation letter — the return date on the visa undertaking form is worked out from this number. If left empty, that box prints as a blank line on the form, just as on the government form.',
    isdCode: "The country code, 880 for Bangladesh. On the e-Arrival card there is a separate small box before the mobile number — put only 880 there and the full number in the next box. If you write them together, the page does not accept it.",
    emergencyPhone: "The number of someone at home you can call in trouble. It is not mandatory on the e-Arrival card, but since you are going for treatment it is good to give one. Not the number of the person travelling with you — they will be with you anyway.",
    airline: "The airline you are flying with — BIMAN BANGLADESH, US-BANGLA, INDIGO. On Air Suvidha this is a dropdown, and the list of flight numbers only appears after you pick it. If travelling by land, leave it empty.",
    flightNo: "The flight number on your ticket — e.g. BG391. On Air Suvidha you do not type it; once you pick the airline you choose it from a list.",
    seatNo: "Seat number — like 14A. You do not know it until you have your boarding pass, so it is fine if you cannot fill it in beforehand. No page other than Air Suvidha needs it.",
    boardingAirport: "The airport you board at, almost always DHAKA (DAC). If you fly directly from Sylhet or Chattogram, write that.",
    arrivalTime: "The time you land in India, as on your ticket — Indian local time, not Bangladesh time (the ticket shows India's). The list has every hour; if your flight lands at 14:35, pick 14:00 — the nearest hour is enough. Nothing but Air Suvidha needs this, so leave it empty if travelling by land.",
    departureDate: "The date you leave Bangladesh. The land port passenger fee is charged against this date, so it needs to be right if you go through Benapole. If flying, just your travel date.",
    landPort: "If going by land, which port. On the Vellore/Kolkata route almost everyone uses BENAPOLE (Haridaspur on the other side). From North Bengal, BANGLABANDHA (Phulbari on the other side) or BURIMARI (Changrabandha on the other side); from the Mymensingh-Sherpur side, NAKUGAON. If flying, leave this empty — then the land port fee button no longer shows either.",
    transportType: "The travel tax amount depends on this. By plane, AIR; through Benapole or another land port, LAND; by waterway, WATER. The Sonali Bank page fills in the amount itself from this, so just pick the right route here — no need to memorise the rates.",
    passengerType: "Under 12 years old, CHILDREN; otherwise ADULT. The travel tax rate for children is different.",
    travelTaxAmount: "The travel tax amount. Best left empty — the Sonali Bank page fills it in itself, and NBR's rates change. No rate is assumed here, because an empty box is better than a wrong amount."
};

export function guideEnFor(field) {
    return field ? FIELD_GUIDE_EN[field.key] || "" : "";
}
