export const LABEL_BN = {
    visaType: "ভিসার ধরন",
    webFileNumber: "ওয়েব ফাইল নম্বর",
    applicationId: "আবেদনের আইডি",
    tempApplicationId: "অস্থায়ী আবেদন আইডি",
    passportNo: "পাসপোর্ট নম্বর",
    fullName: "আবেদনকারীর পুরো নাম",
    gender: "লিঙ্গ",
    dob: "জন্ম তারিখ",
    citizenshipNo: "NID নম্বর",
    surname: "নামের শেষাংশ (Surname)",
    givenName: "নামের প্রথমাংশ (Given Name)",
    changedName: "কখনো নাম বদলেছেন?",
    previousSurname: "আগের Surname",
    previousName: "আগের নাম",
    townOfBirth: "জন্মস্থান",
    countryOfBirth: "জন্মের দেশ",
    nationality: "বর্তমান জাতীয়তা",
    nationalityBy: "নাগরিকত্ব যেভাবে পেয়েছেন",
    previousNationality: "আগের জাতীয়তা",
    religion: "ধর্ম",
    religionOther: "ধর্ম (অন্যান্য হলে)",
    identificationMarks: "শনাক্তকরণ চিহ্ন",
    education: "শিক্ষাগত যোগ্যতা",
    passportCountryOfIssue: "পাসপোর্ট প্রদানকারী দেশ",
    passportPlaceOfIssue: "পাসপোর্ট ইস্যুর স্থান",
    passportIssueDate: "পাসপোর্ট ইস্যুর তারিখ",
    passportExpiryDate: "পাসপোর্টের মেয়াদ শেষের তারিখ",
    otherPassport: "অন্য কোনো পাসপোর্ট আছে?",
    otherPassportCountry: "অন্য পাসপোর্ট — দেশ",
    otherPassportNo: "অন্য পাসপোর্ট — নম্বর",
    otherPassportIssueDate: "অন্য পাসপোর্ট — ইস্যুর তারিখ",
    otherPassportPlaceOfIssue: "অন্য পাসপোর্ট — ইস্যুর স্থান",
    otherPassportNationality: "অন্য পাসপোর্ট — জাতীয়তা",
    presentHouseStreet: "বর্তমান ঠিকানা — বাসা / রোড",
    presentVillageTown: "বর্তমান ঠিকানা — গ্রাম / এলাকা",
    presentCountry: "বর্তমান ঠিকানা — দেশ",
    presentState: "বর্তমান ঠিকানা — বিভাগ",
    presentDistrict: "বর্তমান ঠিকানা — জেলা",
    presentPostal: "বর্তমান ঠিকানা — পোস্ট কোড",
    presentPhone: "ফোন নম্বর",
    presentMobile: "মোবাইল নম্বর",
    presentEmail: "ইমেইল",
    permanentSame: "স্থায়ী ঠিকানা বর্তমানেরটাই?",
    permHouseStreet: "স্থায়ী ঠিকানা — বাসা / রোড",
    permVillageTown: "স্থায়ী ঠিকানা — গ্রাম / এলাকা",
    permState: "স্থায়ী ঠিকানা — বিভাগ",
    permDistrict: "স্থায়ী ঠিকানা — জেলা",
    fatherName: "বাবার নাম",
    fatherNationality: "বাবার জাতীয়তা",
    fatherPrevNationality: "বাবার আগের জাতীয়তা",
    fatherPlaceOfBirth: "বাবার জন্মস্থান",
    fatherCountryOfBirth: "বাবার জন্মের দেশ",
    motherName: "মায়ের নাম",
    motherNationality: "মায়ের জাতীয়তা",
    motherPrevNationality: "মায়ের আগের জাতীয়তা",
    motherPlaceOfBirth: "মায়ের জন্মস্থান",
    motherCountryOfBirth: "মায়ের জন্মের দেশ",
    maritalStatus: "বৈবাহিক অবস্থা",
    spouseName: "স্বামী/স্ত্রীর নাম",
    spouseNationality: "স্বামী/স্ত্রীর জাতীয়তা",
    spousePrevNationality: "স্বামী/স্ত্রীর আগের জাতীয়তা",
    spousePlaceOfBirth: "স্বামী/স্ত্রীর জন্মস্থান",
    spouseCountryOfBirth: "স্বামী/স্ত্রীর জন্মের দেশ",
    grandparentsPak: "দাদা-দাদি/নানা-নানি পাকিস্তানি নাগরিক ছিলেন?",
    grandparentsDetails: "দাদা-দাদি/নানা-নানির বিবরণ",
    occupation: "বর্তমান পেশা",
    occupationOther: "পেশা (অন্যান্য হলে)",
    employerName: "অফিস / প্রতিষ্ঠানের নাম",
    designation: "পদবি",
    employerAddress: "অফিসের ঠিকানা",
    employerPhone: "অফিসের ফোন",
    pastOccupation: "আগের পেশা",
    militaryService: "সেনা / পুলিশ / নিরাপত্তা বাহিনীতে ছিলেন?",
    militaryOrg: "বাহিনীর নাম",
    militaryDesignation: "বাহিনীতে পদবি",
    militaryRank: "র‍্যাংক",
    militaryPosting: "পোস্টিংয়ের স্থান",
    occupationDetailsOf: "কার পেশার তথ্য দেবেন",
    refIndiaName: "ভারতের রেফারেন্স — নাম",
    refIndiaAddress: "ভারতের রেফারেন্স — ঠিকানা",
    refIndiaState: "ভারতের রেফারেন্স — রাজ্য",
    refIndiaDistrict: "ভারতের রেফারেন্স — জেলা",
    refIndiaPhone: "ভারতের রেফারেন্স — ফোন",
    refHomeName: "দেশের রেফারেন্স — নাম",
    refHomeAddress: "দেশের রেফারেন্স — ঠিকানা",
    refHomeAddress2: "দেশের রেফারেন্স — ঠিকানা (২য় লাইন)",
    refHomePhone: "দেশের রেফারেন্স — ফোন",
    visaPurpose: "ভারতে যাওয়ার উদ্দেশ্য",
    arrivalDate: "ভারতে পৌঁছানোর সম্ভাব্য তারিখ",
    mission: "ইন্ডিয়ান মিশন",
    durationDays: "ভিসার মেয়াদ (মাস)",
    noOfEntries: "কতবার প্রবেশ",
    portOfArrival: "প্রবেশ বন্দর",
    portOfExit: "বহির্গমন বন্দর",
    placesToVisit: "যেসব জায়গায় যাবেন",
    medicalRole: "রোগী না অ্যাটেনডেন্ট?",
    attendantOf: "রোগীর নাম",
    attendantOfPassport: "রোগীর পাসপোর্ট নম্বর",
    illness: "রোগ / চিকিৎসার ধরন",
    hospitalName: "ভারতের হাসপাতালের নাম",
    hospitalAddress: "ভারতের হাসপাতালের ঠিকানা",
    doctorName: "ভারতের ডাক্তারের নাম",
    hospitalPhone: "ভারতের হাসপাতালের ফোন",
    hospitalEmail: "ভারতের হাসপাতালের ইমেইল",
    medicalCertNo: "মেডিকেল সার্টিফিকেট / অ্যাপয়েন্টমেন্ট নম্বর",
    homeHospitalName: "দেশের হাসপাতালের নাম",
    homeHospitalAddress: "দেশের হাসপাতালের ঠিকানা",
    homeDoctorName: "দেশের ডাক্তারের নাম",
    homeHospitalPhone: "দেশের হাসপাতালের ফোন",
    homeHospitalEmail: "দেশের হাসপাতালের ইমেইল",
    hasPreviousVisa: "আগে ভারতীয় ভিসা ছিল?",
    visaRefused: "কখনো ভিসা প্রত্যাখ্যাত হয়েছে?",
    saarcVisited: "গত ৩ বছরে সার্ক দেশে গেছেন?",
    oldVisaNo: "আগের ভিসা নম্বর",
    oldVisaType: "আগের ভিসার ধরন",
    oldVisaIssuePlace: "আগের ভিসা ইস্যুর স্থান",
    oldVisaIssueDate: "আগের ভিসা ইস্যুর তারিখ",
    prevVisitAddress: "আগের সফরে থাকার ঠিকানা",
    refuseDetails: "প্রত্যাখ্যানের বিবরণ",
    countriesVisited: "গত ১০ বছরে যাওয়া দেশ",
    stayName: "ভারতে থাকার জায়গা / হোটেল",
    stayAddress: "থাকার জায়গার ঠিকানা",
    stayState: "থাকার জায়গা — রাজ্য",
    stayDistrict: "থাকার জায়গা — জেলা",
    stayPhone: "থাকার জায়গার ফোন",
    stayEmail: "থাকার জায়গার ইমেইল",
    attendantOfDob: "রোগীর জন্ম তারিখ",
    attendantOfNationality: "রোগীর জাতীয়তা",
    attendantRelationship: "রোগীর সাথে আপনার সম্পর্ক",
    attendantOfApplicationId: "রোগীর আবেদন আইডি",
    decArrested: "কখনো গ্রেপ্তার / দণ্ডিত হয়েছেন?",
    decDeported: "কখনো প্রবেশে বাধা / ফেরত পাঠানো?",
    decTrafficking: "পাচার / নির্যাতন / জালিয়াতিতে জড়িত?",
    decTerrorism: "সন্ত্রাস / গুপ্তচরবৃত্তি / সহিংসতায় জড়িত?",
    decGlorifyTerror: "সন্ত্রাসের পক্ষে মত দিয়েছেন?",
    decAsylum: "কোথাও আশ্রয় চেয়েছেন?",
    decVerified: "শেষের ঘোষণায় টিক",
    photoCrop: "ছবিতে মুখ কোথায়",
    stayDays: "ভারতে কত দিন থাকবেন",
    isdCode: "ISD কোড",
    emergencyPhone: "জরুরি যোগাযোগ নম্বর",
    airline: "এয়ারলাইন",
    flightNo: "ফ্লাইট নম্বর",
    seatNo: "সিট নম্বর",
    boardingAirport: "যে বিমানবন্দর থেকে উঠবেন",
    arrivalTime: "ভারতে পৌঁছানোর সময়",
    departureDate: "বাংলাদেশ ছাড়ার তারিখ",
    landPort: "স্থলবন্দর",
    transportType: "কীভাবে যাচ্ছেন",
    passengerType: "যাত্রীর ধরন",
    travelTaxAmount: "ভ্রমণ কর (টাকা)"
};

export function labelBnFor(field) {
    return field ? LABEL_BN[field.key] || field.labelBn || field.label : "";
}
